### ISSUE TITLE
Cannot load solc versions for Smart Contract Verification

### ISSUE THREAD

**Issue by timbrinded** [matter-labs/block-explorer#146]
#### 📝 Description

I'm trying to verify a smart contract against a local network, but the smart contract verification piece isn't working. My setup works against test nets, but when running locally i get:

> [!WARNING]   
> Unable to get list of supported Zksolc versions

> [!WARNING]   
> Unable to get list of supported solc versions

#### 🔄 Reproduction Steps

Steps to reproduce the behaviour:
1) `docker-compose up`
2) Navigate to: [http://localhost:3010/contracts/verify](http://localhost:3010/contracts/verify)

#### 🤔 Expected Behavior

Compilers combo boxes populated:
<img width="791" alt="image" src="https://github.com/matter-labs/block-explorer/assets/79199034/08841709-a164-4cf3-abfd-3601787a620c">

#### 😯 Current Behavior

No info available:
<img width="783" alt="image" src="https://github.com/matter-labs/block-explorer/assets/79199034/a6353ab2-fc51-40ef-990c-f5144e770939">

#### 🖥️ Environment

macOS, npm 20.10

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

Doesn't seem to be any errors in worker/app/api logs

**Comment by nonameb3** [comment]
Based on the answer from this [issues](https://github.com/matter-labs/zksync-cli/issues/106). Contract verification for locally running block explorer is not available yet.
