### ISSUE TITLE
zkWilly - Sybil Account Detection Assistance

### ISSUE THREAD

**Issue by goodacres** [matter-labs/block-explorer#198]
#### 📝 Description

We are aware of a large amount of sybil activity on the zkSync main net. On the surface, we guess this is automated/bot activity for individuals looking to qualify for some expected future airdrop of the zkSync governance token.

A week ago, we launched a zkSync whale tracker called zkWilly (https://twitter.com/zkwilly). We process mainnet transactions to detect and report on large transactions.

Whilst looking at the data we process, we have been noticing a lot of potential sybil behaviour where a string of connected accounts transfer amounts between themselves, supposedly to try and qualify for some suspected airdrop in future.

If this data/processing could be of assistance to zkSync then we would be happy to share 🤝

#### 🤔 Rationale

Identification of on-chain sybil activity can be valuable to bolster analytics and preventative mechanisms.

#### 📋 Additional Context

Not a feature per se, but an interesting topic potentially.

**Comment by MexicanAce** [comment]
Closing as a stale issue
