### ISSUE TITLE
Cant write to contract:

### ISSUE THREAD

**Issue by Daargajedan** [matter-labs/block-explorer#255]
#### 📝 Description

Im trying to write to the contract using the explorer

#### 🔄 Reproduction Steps

Steps to reproduce the behaviour
1. Go to a contract like: https://sepolia.explorer.zksync.io/address/0xd098b00477FCFB3D452a9Faa7D418AAbb4Bf210b
2. Go to a contract then the write tab
3. Fill in spender and value 
4. Click write (after connecting the wallet)

#### 🤔 Expected Behavior

Expect it to write the approve wtih 2 arguments to the contract

#### 😯 Current Behavior

Missing an argument for writing to the contract

#### 🖥️ Environment

Chrome

#### 📋 Additional Context

I think the problem is the input not getting to the transaction function, so both are filled in but not reaching the method to write to the contract (could be that the name value is in the way) BEcause the error saying it expects 2 arguments but get 1 argument. 

#### 📎 Log Output

missing argument: passed to contract (count=1, expectedCount=2, code=MISSING_ARGUMENT, version=contracts/5.7.0)

**Comment by PatrickAlphaC** [comment]
I also cannot use the explorer.

For example, on the USDC address: https://explorer.zksync.io/address/0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4#contract

Try putting any valid values in `spender` and `value`

**Comment by sarahschwartz** [comment]
It seems that this issue has been resolved, I'm not able to reproduce. Are still having an issue with this?

**Comment by PatrickAlphaC** [comment]
<img width="842" alt="Screenshot 2024-10-07 at 8 18 49 PM" src="https://github.com/user-attachments/assets/ff575c20-5a29-48ee-9db7-25665e518bfc">

I am still getting this issue.

**Comment by sarahschwartz** [comment]
Thanks! I was finally able to reproduce, and have identified the issue. Fix should be incoming soon!

**Comment by vasyl-ivanchuk** [comment]
Thanks for reporting @Daargajedan @PatrickAlphaC! The problem was that the function argument named `value` was not processed properly. It's been fixed and deployed. Feel free to check it out.
