### ISSUE TITLE
vyper verification for v0.4 and up

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/block-explorer#290]
### 🌟 Feature Request

It looks like [vyper verification should be supported](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/681)

However, attempting to verify, you run into this issue:

1. Here are the list of compatible versions: https://zksync2-mainnet-explorer.zksync.io/contract_verification/vyper_versions
2. Example failed verification: https://explorer.sepolia.era.zksync.dev/contract_verification/27984

But the [zkvyper compiler](https://github.com/matter-labs/zkvyper-bin) supports 0.4.0

Can we please fix?

**Comment by dutterbutter** [comment]
Hey @PatrickAlphaC 👋 👋 

It looks like this should be supported given as you pointed out zkvyper support for 0.4.0 landed in [1.5.1](https://github.com/matter-labs/era-compiler-vyper/blob/main/CHANGELOG.md#151---2024-06-27). 

Let me investigate if its on the block explorer side or our verification service API to resolve!

**Comment by dutterbutter** [comment]
Will be resolved once this [PR](https://github.com/matter-labs/zksync-era/pull/3049) is merged. Thanks for posting 🙏  

I will close out tomorrow when it can be tested!

**Comment by dutterbutter** [comment]
Resolved with the following PRs:
- https://github.com/matter-labs/zksync-era/pull/3049
- https://github.com/matter-labs/hardhat-zksync/pull/1481

Evidence:
- https://sepolia.explorer.zksync.io/address/0x05105Cf0aeBA4c46Db44542a666429996393D3a5#contract
- https://zksync2-mainnet-explorer.zksync.io/contract_verification/vyper_versions

Please test when you can @PatrickAlphaC but closing now! 🚀

**Comment by PatrickAlphaC** [comment]
Working beautifully!
