### ISSUE TITLE
Adding $ZF to zkSync Era token list - zkSwap Finance

### ISSUE THREAD

**Issue by ZkSwapFinance** [matter-labs/block-explorer#88]
#### 📝 Description

We'd like to request adding our token $ZF to zkSync Era token list: https://explorer.zksync.io/tokenlist

> **Token address:** 0x31C2c031fDc9d33e974f327Ab0d9883Eae06cA4A
> **Token name / Project name:** zkSwap Finance
> **Security & Audit report:** https://docs.zkswap.finance/usdzf-token/security-and-audits
> 

#### 🤔 Rationale

**1. Significant Token Price Performance:**  zkSwap Finance token - $ZF, has recently achieved a new All Time High, killed another zero in its price and going trending across social medias

Notable TVL growth: 
-  +140% (1M change) 
-  +88.5% (7D Change)
-   Total TVL $1.3M, ranked 13th on zkSync 
- Impressive Vol: ~800K Daily, and keep increasing

**2. Attract potential users:** Following the hype of our achievement, the listing of $ZF on zkSync Era will potentially enhance liquidity and trading activity, benefiting both the zkSwap Finance community and users of zkSync.

#### 📋 Additional Context

We'd like to discuss further potential partnership opportunities upon listing our token. Our BD - Christ would love to connect with you all
His contact for discussion: https://t.me/zkSwap_Christ 

Best Regards,
zkSwap Finance

**Comment by Romsters** [comment]
Hi @ZkSwapFinance, thanks for submitting the issue, your token is now listed.

**Comment by ZkSwapFinance** [comment]
> Hi @ZkSwapFinance, thanks for submitting the issue, your token is now listed.

Dear @Romsters ,

Thank you so much and Wish you have a nice day!

Best Regards,
Ryan,
zkSwap Finance Team
