### ISSUE TITLE
Add "View all" button to latest transactions table

### ISSUE THREAD

**Issue by JackHamer09** [matter-labs/block-explorer#97]
#### 📝 Description

Add "View all" at the end of Latest Transactions table (if there are more available)
<img width="667" alt="image" src="https://github.com/matter-labs/block-explorer/assets/47187316/ce21c798-fd0b-4a2b-98ce-70d24a9763e2">
We could add same for Latest Batches

#### 🤔 Rationale

When there are not a lot of transactions on the chain (eg when running clean local setup), people may think these are all existing transactions on the chain. People aren't aware that to see all transaction they need to go to "Block Explorer" -> "Transactions" cause it is pretty hidden. 

#### 📋 Additional Context

That's feedback from zkQuest

**Comment by NayanWankhade** [comment]
In that case, can't we implement **View all** button at the bottom of both the **batches and the transactions list**. When user hits View All button, the page should redirect them to https://explorer.zksync.io/transactions/ ( For viewing all transactions list) and https://explorer.zksync.io/batches/ (for viewing all the batches). It will be more practical, I guess.
